services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        USER_ID: '${USER_ID:-1000}'
        GROUP_ID: '${GROUP_ID:-1000}'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    #ports:
      #- '${VITE_APP_PORT:-5173}:${VITE_APP_PORT:-5173}' # Not necessarily required for dev containers (auto port forwarding)
    environment:
      PHP_OPCACHE_ENABLE: '1'
      PHP_OPCACHE_REVALIDATE_FREQ: '0'
      XDEBUG_MODE: '${XDEBUG_MODE:-off}'
    volumes:
      - '.:/var/www/html'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.laravel-nuxtui.rule=Host(`${APP_DOMAIN}`)'
      - 'traefik.http.services.laravel-nuxtui.loadbalancer.server.port=8080' # exposed http port from serversideup image
    networks:
      - proxy
      - laravel

networks:
  laravel:
  proxy:
    name: traefik_proxy
    external: true
